### ISSUE TITLE
PALgen issue

### ISSUE THREAD

**Issue by eugene-s-nesdev** [alaahadid/My-Nes#1] opened 2021-03-16 12:59 UTC
Current palette generator can switch between **NTSC/Dendy** and **PALB**.
This is incorrect because Dendy is PAL machine working on NTSC-like CPU/PPU internal timings:
https://forums.nesdev.com/viewtopic.php?f=2&t=20931

So, switch between **NTSC** and **PALB/Dendy** must be correct.

![pal](https://user-images.githubusercontent.com/13199529/111312774-afdeb780-8670-11eb-84cb-958cc2224aa3.png)

**Comment by alaahadid** [comment] 2021-03-20 00:00
Hello,
The issue was with the text in the settings window (not effect emulation, i.e. NTSC palette is for NTSC, PALB palette is for PALB or DENDY), it is fixed now with the [new release 7.8.7748.43133 ](https://github.com/alaahadid/My-Nes/releases/tag/v7.8.7748.43133). Also, DENDY and PALB timings are fixed in this version, all PALB and DENDY games should work without errors in this version.

**Comment by eugene-s-nesdev** [comment] 2021-03-20 10:56
Thank you!
Can you make 4:3 aspect ratio option (like other emulators have) please?
![aspect](https://user-images.githubusercontent.com/13199529/111867276-fc353a80-8983-11eb-8484-f6e83c2ee29a.png)

**Comment by eugene-s-nesdev** [comment] 2021-03-20 11:00
[GITS_2_by_Sergey_Ryumik_ENG.zip](https://github.com/alaahadid/My-Nes/files/6175383/GITS_2_by_Sergey_Ryumik_ENG.zip)

**Comment by alaahadid** [comment] 2021-03-20 19:21
I think My Nes already implemented something like that "Keep Aspect Ratio" but that option tries to keep the aspect ration related to ne res which is 256 x 240 (or 256 x 224 in NTSC). I think the 4:3 standard is related to NTSC tv standard res but not implemented in My Nes yet. I'll try to implement this in the next version in My Nes. Thanks !!

**Comment by alaahadid** [comment] 2021-04-27 14:08
Hi again, i have implemented the TV Standard 4:3, you can check it out here: [in this release 7.8.7787.28283](https://github.com/alaahadid/My-Nes/releases/tag/v7.8.7787.28283). I have tried this test file GITS_2_by_Sergey_Ryumik_ENG.zip it looked different and not as in the snap you posted, My Nes uses [Analog TV Standards](https://gist.github.com/jonlabelle/7834592). If it is all ok let me know :)

**Comment by eugene-s-nesdev** [comment] 2021-04-29 11:51
Is it working?
![mynes](https://user-images.githubusercontent.com/13199529/116546460-4e119e80-a8fa-11eb-87e1-9082d224ce57.png)

**Comment by alaahadid** [comment] 2021-04-29 15:13
It was a mistake, instead of implementing 486 x 440 video size for NTSC I need to implement 640 x 320 video size. See <https://en.wikipedia.org/wiki/Pixel_aspect_ratio>. I will work on this ASAP.

**Comment by alaahadid** [comment] 2021-04-29 22:29
I think the problem is fixed now with [version 7.7790.509](https://github.com/alaahadid/My-Nes/releases/tag/v7.9.7790.509), resolution is set to 640 x 480 which is NTSC standard. Also, My Nes outputs video now with res 640 x 480. Please tell me what you think.

**Comment by alaahadid** [comment] 2021-04-29 22:55
I forgot to mention that only SDL2 Video Renderer support 640x480 res output, the other output 256 x 240 stretched into 640 x 480.

**Comment by eugene-s-nesdev** [comment] 2021-04-30 08:11
Does "keep aspect ratio" checkbox working correct in all 1x/2x etc modes?
Seems that stretch modes don't work on-the-fly. Need to change region for apply...

[video.zip](https://github.com/alaahadid/My-Nes/files/6403821/video.zip)

**Comment by alaahadid** [comment] 2021-05-01 00:25
New release of My Nes <https://github.com/alaahadid/My-Nes/releases/tag/v7.9.7791.3517> allows to switch rendering res. "Keep aspect ratio" only tries to stretch the image displayed to keep the aspect ratio of selected res, for example, res 640 x 480 is 4:3, the windows size is 1024 x 700, keep aspect ratio will try to stretch 640 x 480 image into 1024 x 700 with keeping aspect ratio of 4:3. Keep aspect ratio option should work with all resolutions selected.

I'll look at sound filters are not enabled in Audio issue ASAP.

**Comment by alaahadid** [comment] 2021-05-03 12:02
The issue has been resolved after version <https://github.com/alaahadid/My-Nes/releases/tag/v7.9.7791.3517>. For audio issue please open new issue topic. This topic is closed.

**Closed by alaahadid** 2021-05-03 12:02 UTC
